import { useEffect, useState } from 'react'
import Flash from '../../components/ui/Flash'
import { apiRequest } from '../../lib/api'
import { formatMoney } from '../../lib/format'
import { useAuth } from '../auth/AuthContext'

export default function DashboardPage() {
  const { user, logout } = useAuth(); const [data, setData] = useState(null); const [error, setError] = useState('')
  useEffect(() => { apiRequest('/dashboard').then(setData).catch((e) => setError(e.message)) }, [])
  if (!data) return <section className="mx-auto max-w-7xl px-4 py-6 md:px-8 md:py-8">{error ? <Flash message={error} tone="error" /> : <div className="budget-panel text-sm text-slate-500">Loading...</div>}</section>
  const cards = [['Total Balance', data.total_balance, 'primary', 'Seluruh transaksi Anda'], ['Total Income', data.total_income, 'success', 'Akumulasi pemasukan'], ['Total Expenses', data.total_expenses, 'danger', 'Akumulasi pengeluaran']]
  const maxExpense = Math.max(...data.expense_by_category.map((item) => Number(item.total_amount)), 1)
  const badge = { good: 'budget-badge-success', warn: 'budget-badge-warn', danger: 'budget-badge-danger' }; const bar = { good: 'bg-emerald-500', warn: 'bg-amber-500', danger: 'bg-rose-500' }
  return <section className="mx-auto max-w-7xl space-y-8 px-4 py-6 md:px-8 md:py-8"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-bold text-slate-900">Dashboard</h1><p className="mt-1 text-sm text-slate-500">Welcome back, {user.name}! Here's your financial overview.</p></div><button onClick={logout} className="budget-button budget-button-danger">Logout</button></div><div className="grid gap-4 md:grid-cols-3">{cards.map(([label, amount, tone, meta]) => <article key={label} className={`budget-card budget-card-${tone}`}><p className="budget-label">{label}</p><p className="budget-amount">{formatMoney(amount)}</p><p className="budget-meta">{meta}</p></article>)}</div><div className="grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(18rem,1fr)]"><section className="budget-panel"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-900">Expenses by Category</h2><p className="mt-1 text-sm text-slate-500">Pengeluaran bulan berjalan berdasarkan kategori.</p></div><span className="budget-pill">{data.current_month_label}</span></div><div className="mt-8 space-y-5">{data.expense_by_category.length ? data.expense_by_category.map((item) => <div key={item.category_name} className="space-y-2"><div className="flex items-center justify-between text-sm"><span className="font-medium text-slate-700">{item.category_name}</span><span className="text-slate-500">{formatMoney(item.total_amount)}</span></div><div className="budget-progress-track"><div className="budget-progress-fill bg-blue-500" style={{ width: `${Math.min(100, Math.round(Number(item.total_amount) / maxExpense * 100))}%` }} /></div></div>) : <p className="rounded-2xl border border-dashed border-slate-200 px-4 py-6 text-sm text-slate-500">Belum ada pengeluaran bulan ini.</p>}</div></section><section className="budget-panel"><div><h2 className="text-lg font-semibold text-slate-900">Budget Usage</h2><p className="mt-1 text-sm text-slate-500">Pemakaian budget aktif pada bulan berjalan.</p></div><div className="mt-6 space-y-5">{data.budget_usage.length ? data.budget_usage.map((item) => <div key={item.category} className="space-y-2"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-800">{item.category}</p><p className="text-xs text-slate-500">{formatMoney(item.spent)} of {formatMoney(item.limit)}</p></div><span className={`budget-badge ${badge[item.status]}`}>{item.percentage}%</span></div><div className="budget-progress-track"><div className={`budget-progress-fill ${bar[item.status]}`} style={{ width: `${item.percentage}%` }} /></div></div>) : <p className="rounded-2xl border border-dashed border-slate-200 px-4 py-6 text-sm text-slate-500">Belum ada budget aktif.</p>}</div></section></div></section>
}
