import { useState } from 'react'
import Field from '../../components/ui/Field'
import Flash from '../../components/ui/Flash'
import { apiPut } from '../../lib/api'
import { useAuth } from '../auth/AuthContext'

export default function SettingsPage() {
  const { user, updateUser } = useAuth(); const [profile, setProfile] = useState({ name: user.name, email: user.email }); const [password, setPassword] = useState({ current_password: '', password: '', password_confirmation: '' }); const [profileErrors, setProfileErrors] = useState({}); const [passwordErrors, setPasswordErrors] = useState({}); const [status, setStatus] = useState(''); const [error, setError] = useState('')
  async function saveProfile(event) { event.preventDefault(); setProfileErrors({}); setError(''); try { const updated = await apiPut('/settings/profile', profile); updateUser(updated); setStatus('Profil berhasil diperbarui.') } catch (e) { setProfileErrors(e.errors ?? {}); setError(e.message) } }
  async function savePassword(event) { event.preventDefault(); if (password.password !== password.password_confirmation) { setPasswordErrors({ password: ['password confirmation does not match'] }); return } setPasswordErrors({}); setError(''); try { await apiPut('/settings/password', password); setPassword({ current_password: '', password: '', password_confirmation: '' }); setStatus('Password berhasil diperbarui.') } catch (e) { setPasswordErrors(e.errors ?? {}); setError(e.message) } }
  return <section className="mx-auto max-w-3xl space-y-6 px-4 py-6 md:px-8 md:py-8"><div><h1 className="text-3xl font-bold text-slate-900">Settings</h1><p className="mt-1 text-sm text-slate-500">Manage your account preferences.</p></div>{status && <Flash message={status} />}{error && <Flash message={error} tone="error" />}<section className="budget-panel space-y-5"><div><h2 className="text-xl font-semibold text-slate-900">Profile Settings</h2><p className="mt-1 text-sm text-slate-500">Perbarui nama dan email akun Anda.</p></div><form onSubmit={saveProfile} className="space-y-4"><Field label="Account Name" error={profileErrors.name?.[0]}><input type="text" value={profile.name} onChange={(e) => setProfile({ ...profile, name: e.target.value })} required /></Field><Field label="Email" error={profileErrors.email?.[0]}><input type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} required /></Field><button type="submit" className="budget-button budget-button-primary">Save Profile</button></form></section><section className="budget-panel space-y-5"><div><h2 className="text-xl font-semibold text-slate-900">Password Settings</h2><p className="mt-1 text-sm text-slate-500">Ganti password akun Anda dengan verifikasi password saat ini.</p></div><form onSubmit={savePassword} className="space-y-4"><Field label="Current Password" error={passwordErrors.current_password?.[0]}><input type="password" value={password.current_password} onChange={(e) => setPassword({ ...password, current_password: e.target.value })} required /></Field><Field label="New Password" error={passwordErrors.password?.[0]}><input type="password" value={password.password} onChange={(e) => setPassword({ ...password, password: e.target.value })} required minLength={8} /></Field><Field label="Confirm New Password"><input type="password" value={password.password_confirmation} onChange={(e) => setPassword({ ...password, password_confirmation: e.target.value })} required /></Field><button type="submit" className="budget-button budget-button-primary">Update Password</button></form></section><section className="budget-panel border-dashed bg-slate-50"><p className="text-sm leading-6 text-slate-500">Fitur export dan clear data belum tersedia pada versi ini.</p></section></section>
}
