import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import Flash from '../../components/ui/Flash'
import { apiDelete, apiRequest } from '../../lib/api'
import { formatMoney, monthName } from '../../lib/format'

export default function BudgetsPage() {
  const [budgets, setBudgets] = useState(null)
  const [error, setError] = useState('')
  useEffect(() => { apiRequest('/budgets').then(setBudgets).catch((e) => setError(e.message)) }, [])
  async function destroy(item) { if (!window.confirm('Hapus budget ini?')) return; try { await apiDelete(`/budgets/${item.id}`); setBudgets((all) => all.filter((row) => row.id !== item.id)) } catch (e) { setError(e.message) } }
  return <section className="mx-auto max-w-5xl space-y-8 px-4 py-6 md:px-8 md:py-8"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-bold text-slate-900">Budgets</h1><p className="mt-1 text-sm text-slate-500">Set and manage your spending limits.</p></div><Link to="/budgets/create" className="budget-button budget-button-primary">Add Budget</Link></div>{error && <Flash message={error} tone="error" />}{!budgets ? <div className="budget-panel text-sm text-slate-500">Loading...</div> : budgets.length === 0 ? <section className="budget-panel text-center"><h2 className="text-xl font-semibold text-slate-900">Belum ada budget</h2><p className="mt-2 text-sm text-slate-500">Buat budget bulanan pertama Anda untuk mulai mengatur pengeluaran.</p><Link to="/budgets/create" className="budget-button budget-button-primary mt-6">Create First Budget</Link></section> : <div className="space-y-4">{budgets.map((budget) => <article key={budget.id} className="budget-panel"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div className="space-y-2"><div className="flex items-center gap-3"><h2 className="text-lg font-semibold text-slate-900">{budget.category.name}</h2><span className="budget-badge budget-badge-danger">Expense</span></div><p className="text-sm text-slate-500">Period: {monthName(budget.month)} {budget.year}</p></div><div className="flex items-center gap-3"><Link to={`/budgets/${budget.id}/edit`} className="budget-button budget-button-secondary px-4 py-2">Edit</Link><button onClick={() => destroy(budget)} className="budget-button budget-button-danger px-4 py-2">Delete</button></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Budget Limit</p><p className="mt-2 text-2xl font-bold text-slate-900">{formatMoney(budget.limit_amount)}</p></div><div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Category</p><p className="mt-2 text-2xl font-bold text-slate-900">{budget.category.name}</p></div></div></article>)}</div>}</section>
}
