import { useEffect, useState } from 'react'
import Flash from '../../components/ui/Flash'
import { apiRequest } from '../../lib/api'
import { formatMoney, monthName } from '../../lib/format'

export default function ReportsPage() {
  const now = new Date(); const initial = { month: now.getMonth() + 1, year: now.getFullYear() }; const [filters, setFilters] = useState(initial); const [period, setPeriod] = useState(initial); const [data, setData] = useState(null); const [error, setError] = useState('')
  useEffect(() => { setData(null); apiRequest(`/reports/summary?month=${period.month}&year=${period.year}`).then(setData).catch((e) => setError(e.message)) }, [period])
  function apply(event) { event.preventDefault(); setPeriod({ month: Number(filters.month), year: Number(filters.year) }) }
  function reset() { setFilters(initial); setPeriod(initial) }
  const year = now.getFullYear(); const label = data ? `${monthName(data.month)} ${data.year}` : ''
  const breakdown = (title, copy, items, color, empty) => {
    items = items ?? []
    const max = Math.max(...items.map((item) => Number(item.total_amount)), 1)
    return <section className="budget-panel"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-900">{title}</h2><p className="text-sm text-slate-500">{copy}</p></div><span className="budget-pill">{label}</span></div><div className="mt-8 space-y-5">{items.length ? items.map((item) => <div key={item.category_name} className="space-y-2"><div className="flex items-center justify-between text-sm"><span className="font-medium text-slate-700">{item.category_name}</span><span className="text-slate-500">{formatMoney(item.total_amount)}</span></div><div className="budget-progress-track"><div className={`budget-progress-fill ${color}`} style={{ width: `${Math.min(100, Math.round(Number(item.total_amount) / max * 100))}%` }} /></div></div>) : <p className="rounded-2xl border border-dashed border-slate-200 px-4 py-6 text-sm text-slate-500">{empty}</p>}</div></section>
  }
  return <section className="mx-auto max-w-6xl space-y-8 px-4 py-6 md:px-8 md:py-8"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-bold text-slate-900">Reports</h1><p className="mt-1 text-sm text-slate-500">Analyze your financial trends and patterns.</p></div><form onSubmit={apply} className="grid gap-3 sm:grid-cols-2 lg:flex lg:items-end"><label className="budget-field min-w-[10rem]"><span>Month</span><select value={filters.month} onChange={(e) => setFilters({ ...filters, month: e.target.value })}>{Array.from({ length: 12 }, (_, i) => i + 1).map((month) => <option key={month} value={month}>{monthName(month)}</option>)}</select></label><label className="budget-field min-w-[8rem]"><span>Year</span><select value={filters.year} onChange={(e) => setFilters({ ...filters, year: e.target.value })}>{[year - 1, year, year + 1].map((item) => <option key={item}>{item}</option>)}</select></label><div className="flex gap-3"><button type="submit" className="budget-button budget-button-primary">Apply</button><button type="button" onClick={reset} className="budget-button budget-button-secondary">Reset</button></div></form></div>{error && <Flash message={error} tone="error" />}{!data ? <div className="budget-panel text-sm text-slate-500">Loading...</div> : <><div className="grid gap-4 md:grid-cols-3">{[['Total Income', data.total_income, 'success'], ['Total Expenses', data.total_expenses, 'danger'], ['Net Savings', data.net_savings, 'primary']].map(([title, amount, tone]) => <article key={title} className={`budget-card budget-card-${tone}`}><p className="budget-label">{title}</p><p className="budget-amount">{formatMoney(amount)}</p><p className="budget-meta">{label}</p></article>)}</div><div className="grid gap-6 xl:grid-cols-2">{breakdown('Income by Category', 'Breakdown pemasukan pada periode terpilih.', data.income_by_category, 'bg-emerald-500', 'Belum ada pemasukan pada periode ini.')}{breakdown('Expense by Category', 'Breakdown pengeluaran pada periode terpilih.', data.expense_by_category, 'bg-rose-500', 'Belum ada pengeluaran pada periode ini.')}</div></>}</section>
}
